export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const AUTH_LOGIN_PENDING = 'AUTH_LOGIN_PENDING';

export const AUTH_LOGIN_ERROR_NETWORK = 'AUTH_LOGIN_ERROR_NETWORK';
